version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npx prisma migrate deploy && node server.js"
    ports:
      - 3005:3000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/myapp?schema=public
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d myapp"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data: