version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3005:3000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/myapp?schema=public
      - OPENAI_API_KEY=
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp

volumes:
  db-data: